=== vicmacarras/MAZDATA/fallos.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT coches (coche)+>
<!ATTLIST coches
  xmlns CDATA #FIXED ''>

<!ELEMENT coche (GENERACION,FALLO)>
<!ATTLIST coche
  xmlns CDATA #FIXED ''>

<!ELEMENT GENERACION (#PCDATA)>
<!ATTLIST GENERACION
  xmlns CDATA #FIXED ''>

<!ELEMENT FALLO (#PCDATA)>
<!ATTLIST FALLO
  xmlns CDATA #FIXED ''>

=== vicmacarras/MAZDATA/fallos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="fallos.xsl"?>
<!DOCTYPE coches SYSTEM "fallos.dtd">
<coches>
  <coche>
    <GENERACION>NA</GENERACION>
    <FALLO>Junta de la trocola</FALLO>
  </coche>
  <coche>
    <GENERACION>ND</GENERACION>
    <FALLO>Transmision</FALLO>
  </coche>
  <coche>
    <GENERACION>NA</GENERACION>
    <FALLO>Motor Ventanas</FALLO>
  </coche>
  <coche>
    <GENERACION>NB</GENERACION>
    <FALLO>Varilla Aceite(rotura)</FALLO>
  </coche>
  <coche>
    <GENERACION>NA</GENERACION>
    <FALLO>Diferencial </FALLO>
  </coche>
</coches>
